services:
  - type: web
    name: portfolio-website
    env: python
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: cd portfolio_project && gunicorn portfolio_project.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: localhost,127.0.0.1,.onrender.com
      - key: PIP_NO_CACHE_DIR
        value: "1"
      - key: PIP_DISABLE_PIP_VERSION_CHECK
        value: "1"
      - key: DATABASE_URL
        value: postgresql://portfolio_u2pz_user:8HKmUljB5ESxLwDwuR9Wa6kk10DqFE8K@dpg-d27fkmmuk2gs73e47g30-a.oregon-postgres.render.com/portfolio_u2pz
    autoDeploy: true 