services:
  - type: web
    name: portfolio-website
    env: python
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: cd portfolio_project && gunicorn portfolio_project.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: localhost,127.0.0.1,.onrender.com
      - key: PIP_NO_CACHE_DIR
        value: "1"
      - key: PIP_DISABLE_PIP_VERSION_CHECK
        value: "1"
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString
    autoDeploy: true

databases:
  - name: portfolio-db
    databaseName: portfolio
    user: portfolio 