# Generated by Django 4.2.7 on 2025-08-03 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_aboutcontent_contactinfo_project_resumesection_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ResumeSection',
        ),
    ]
